"---General--------------------------------------------------------------
"  Show line number
set number
" open a NERDTree automatically when vim starts up
autocmd vimenter * NERDTree
" Ctrl+n to open NERDtree
map <C-n> :NERDTreeToggle<CR>
" close vim if the only window left open is NERDtree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
" use alt to move between windows
nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>

nmap <silent> <A-k> :wincmd k<CR>
nmap <silent> <A-j> :wincmd j<CR>
nmap <silent> <A-h> :wincmd h<CR>
nmap <silent> <A-l> :wincmd l<CR>


syntax enable

" to use custom colorscheme in vim/colors
" colorscheme mine
"---Vundle Config--------------------------------------------------------
set nocompatible              " be iMproved, required
filetype off                  " required
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'
" ES2015 code snippets (Optional)
Plugin 'epilande/vim-es2015-snippets'
" React code snippets
Plugin 'epilande/vim-react-snippets'
" Ultisnips
Plugin 'SirVer/ultisnips'
" Emmet plugin for html tags
Plugin 'mattn/emmet-vim'

Plugin 'prettier/vim-prettier'

Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
" --- end of Vundle config ------------------------------------
" Trigger configuration (Optional)
let g:UltiSnipsExpandTrigger="<C-l>"
let g:user_emmet_leader_key='<C-m>'
